import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Mail, Sparkles, ArrowRight, Clock } from "lucide-react";
import { useNavigate } from "react-router-dom";

export const EmailQueueEmptyState = () => {
  const navigate = useNavigate();

  return (
    <div className="flex items-center justify-center min-h-[calc(100vh-200px)] animate-fade-in px-4">
      <div className="max-w-4xl w-full">
        {/* Hero Section */}
        <div className="text-center mb-12">
          <div className="inline-flex items-center justify-center w-24 h-24 rounded-2xl bg-gradient-to-br from-primary/20 to-primary/5 mb-6">
            <Mail className="w-12 h-12 text-primary" />
          </div>
          
          <h1 className="text-4xl font-bold mb-4">AI-Powered Email Queue</h1>
          
          <p className="text-xl text-muted-foreground mb-6 max-w-2xl mx-auto">
            Personalized emails generated by AI to activate your users
          </p>

          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 border border-primary/20">
            <Sparkles className="w-4 h-4 text-primary" />
            <span className="text-sm font-medium text-primary">Ready within 24 hours of first benchmark</span>
          </div>
        </div>

        {/* Process Steps */}
        <div className="mb-8">
          <h2 className="text-2xl font-bold text-center mb-6">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-4">
            <Card className="p-6 text-center border-2 hover:border-primary/30 transition-colors">
              <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-primary text-primary-foreground font-bold text-xl mb-4">
                1
              </div>
              <h3 className="font-semibold mb-2">Define Success</h3>
              <p className="text-sm text-muted-foreground">
                Mark users who achieved activation as benchmarks
              </p>
            </Card>

            <Card className="p-6 text-center border-2 hover:border-primary/30 transition-colors">
              <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-primary text-primary-foreground font-bold text-xl mb-4">
                2
              </div>
              <h3 className="font-semibold mb-2">AI Analysis</h3>
              <p className="text-sm text-muted-foreground">
                Identifies users with similar behavior patterns
              </p>
            </Card>

            <Card className="p-6 text-center border-2 hover:border-primary/30 transition-colors">
              <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-primary text-primary-foreground font-bold text-xl mb-4">
                3
              </div>
              <h3 className="font-semibold mb-2">Draft Emails</h3>
              <p className="text-sm text-muted-foreground">
                Generates personalized content based on their journey
              </p>
            </Card>

            <Card className="p-6 text-center border-2 hover:border-primary/30 transition-colors">
              <div className="inline-flex items-center justify-center w-12 h-12 rounded-full bg-primary text-primary-foreground font-bold text-xl mb-4">
                4
              </div>
              <h3 className="font-semibold mb-2">Review & Send</h3>
              <p className="text-sm text-muted-foreground">
                You approve, edit, or reject before sending
              </p>
            </Card>
          </div>
        </div>

        {/* Features Preview */}
        <div className="grid md:grid-cols-2 gap-6 mb-8">
          <Card className="p-6 border-2">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center shrink-0">
                <Sparkles className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-2">Smart Personalization</h3>
                <p className="text-sm text-muted-foreground mb-3">
                  Every email is tailored to the user's specific journey, actions, and context
                </p>
                <div className="space-y-1 text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>References their actual behavior</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>Contextual feature suggestions</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>Optimal timing based on patterns</span>
                  </div>
                </div>
              </div>
            </div>
          </Card>

          <Card className="p-6 border-2">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-lg bg-success/10 flex items-center justify-center shrink-0">
                <Mail className="w-6 h-6 text-success" />
              </div>
              <div>
                <h3 className="font-semibold text-lg mb-2">Full Control</h3>
                <p className="text-sm text-muted-foreground mb-3">
                  You're always in the driver's seat with every email draft
                </p>
                <div className="space-y-1 text-xs text-muted-foreground">
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>Review before sending</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>Edit content freely</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="w-1 h-1 rounded-full bg-primary" />
                    <span>Approve or reject drafts</span>
                  </div>
                </div>
              </div>
            </div>
          </Card>
        </div>

        {/* CTA Section */}
        <Card className="p-8 bg-gradient-to-br from-primary/5 via-primary/10 to-primary/5 border-primary/20">
          <div className="flex flex-col md:flex-row items-center justify-between gap-6">
            <div className="flex items-start gap-4 text-left">
              <div className="w-12 h-12 rounded-lg bg-primary/20 flex items-center justify-center shrink-0">
                <Clock className="w-6 h-6 text-primary" />
              </div>
              <div>
                <h3 className="text-xl font-bold mb-2">Start Getting Email Drafts</h3>
                <p className="text-muted-foreground">
                  Mark your first benchmark users to activate AI email generation
                </p>
              </div>
            </div>
            <Button
              size="lg"
              onClick={() => navigate("/home")}
              className="gap-2 bg-gradient-to-r from-primary to-primary/90 hover:opacity-90 shrink-0"
            >
              Set Benchmarks
              <ArrowRight className="w-4 h-4" />
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
};
